### ISSUE TITLE
CircleCI showing up on status

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/dask-gateway-feedstock#37]
On commit ( https://github.com/conda-forge/dask-gateway-feedstock/commit/6b61b6980b5d798859afddc7c911d484a41c217f ), CircleCI is showing up noting the config is missing (related [CircleCI job]( 
https://app.circleci.com/pipelines/github/conda-forge/dask-gateway-feedstock/72 )).

<img width="1840" alt="Screen Shot 2023-01-11 at 2 21 32 PM" src="https://user-images.githubusercontent.com/3019665/211930460-ff074717-4696-4ff5-955c-954169fdd59c.png">

**Comment by jakirkham** [comment]
@conda-forge/core, how do we handle this? Should we just remove CircleCI from here? Or is there something else we should do?

**Comment by beckermr** [comment]
I deleted the webhook. This won't happen again.

**Comment by jakirkham** [comment]
Thanks Matt! 🙏
